// ─── Cóndor Club Salud Service ───────────────────────────────
// Patient membership management with teleconsultas and medical benefits.
// Plans: Básico ($9,000), Plus ($24,500), Familiar ($90,000).
// ──────────────────────────────────────────────────────────────
// NOTE: Uses SUPABASE_SERVICE_ROLE_KEY for all DB access because
// Condor Salud uses custom `condor_session` cookie auth, NOT
// Supabase Auth. The anon-key client from @/lib/supabase/server
// cannot pass RLS policies for INSERT/UPDATE operations.
// ──────────────────────────────────────────────────────────────

import { type SupabaseClient } from "@supabase/supabase-js";
import { logger } from "@/lib/logger";
import { isSupabaseConfigured } from "@/lib/env";
import type { ClubPlan, ClubMembership, PrescriptionFee } from "@/lib/types";

// ─── Helpers ─────────────────────────────────────────────────

async function getSupabase(): Promise<SupabaseClient> {
  if (!isSupabaseConfigured()) throw new Error("Supabase not configured");
  const { createClient } = await import("@supabase/supabase-js");
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );
}

// ─── Club Plans ──────────────────────────────────────────────

/** Get all active club plans, sorted */
export async function getClubPlans(): Promise<ClubPlan[]> {
  const supabase = await getSupabase();
  const { data, error } = await supabase
    .from("club_plans")
    .select("*")
    .eq("active", true)
    .order("sort_order");

  if (error) {
    logger.error({ error }, "Failed to fetch club plans");
    throw new Error("Failed to fetch club plans");
  }

  return (data || []).map(mapPlan);
}

/** Get a single plan by slug */
export async function getClubPlanBySlug(slug: string): Promise<ClubPlan | null> {
  const supabase = await getSupabase();
  const { data, error } = await supabase.from("club_plans").select("*").eq("slug", slug).single();

  if (error || !data) return null;
  return mapPlan(data);
}

// ─── Memberships ─────────────────────────────────────────────

/** Check if a patient has an active club membership */
export async function getActiveMembership(patientId: string): Promise<ClubMembership | null> {
  const supabase = await getSupabase();
  const { data, error } = await supabase
    .from("club_memberships")
    .select("*, club_plans(*)")
    .eq("patient_id", patientId)
    .eq("status", "active")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (error || !data) return null;
  return mapMembership(data);
}

/** Check if patient is a club member (quick boolean) */
export async function isClubMember(patientId: string): Promise<boolean> {
  const membership = await getActiveMembership(patientId);
  return membership !== null;
}

/** Create a new club membership */
export async function createMembership(input: {
  patientId: string;
  planSlug: string;
  mpSubscriptionId?: string;
}): Promise<ClubMembership> {
  const plan = await getClubPlanBySlug(input.planSlug);
  if (!plan) throw new Error(`Unknown plan: ${input.planSlug}`);

  // Cancel any existing active membership first
  const existing = await getActiveMembership(input.patientId);
  if (existing) {
    await cancelMembership(input.patientId, "upgraded");
  }

  const supabase = await getSupabase();

  // member_id is auto-generated by the DB DEFAULT via club_member_id_seq
  // Format: CS-XXXXXX (e.g., CS-100001)

  const { data, error } = await supabase
    .from("club_memberships")
    .insert({
      patient_id: input.patientId,
      plan_id: plan.id,
      status: "active",
      mp_subscription_id: input.mpSubscriptionId || null,
      started_at: new Date().toISOString(),
      expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    })
    .select("*, club_plans(*)")
    .single();

  if (error || !data) {
    logger.error({ error }, "Failed to create club membership");
    throw new Error("Failed to create membership");
  }

  logger.info({ patientId: input.patientId, plan: input.planSlug }, "Club membership created");
  return mapMembership(data);
}

/** Get a membership by its public member ID (CS-XXXXXX) */
export async function getMembershipByMemberId(memberId: string): Promise<ClubMembership | null> {
  const supabase = await getSupabase();
  const { data, error } = await supabase
    .from("club_memberships")
    .select("*, club_plans(*)")
    .eq("member_id", memberId)
    .eq("status", "active")
    .maybeSingle();

  if (error || !data) return null;
  return mapMembership(data);
}

/** Cancel a patient's active membership */
export async function cancelMembership(patientId: string, reason?: string): Promise<void> {
  const supabase = await getSupabase();
  const { error } = await supabase
    .from("club_memberships")
    .update({
      status: "cancelled",
      cancelled_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })
    .eq("patient_id", patientId)
    .eq("status", "active");

  if (error) {
    logger.error({ error }, "Failed to cancel membership");
    throw new Error("Failed to cancel membership");
  }

  logger.info({ patientId, reason }, "Club membership cancelled");
}

/** Process MercadoPago subscription webhook for renewals */
export async function processSubscriptionWebhook(payload: {
  subscriptionId: string;
  status: "authorized" | "paused" | "cancelled";
}): Promise<void> {
  const supabase = await getSupabase();

  if (payload.status === "cancelled") {
    await supabase
      .from("club_memberships")
      .update({
        status: "cancelled",
        cancelled_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq("mp_subscription_id", payload.subscriptionId)
      .eq("status", "active");
    return;
  }

  if (payload.status === "authorized") {
    // Renew — extend expiration by 30 days
    await supabase
      .from("club_memberships")
      .update({
        expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq("mp_subscription_id", payload.subscriptionId)
      .eq("status", "active");
    return;
  }

  if (payload.status === "paused") {
    await supabase
      .from("club_memberships")
      .update({ status: "paused", updated_at: new Date().toISOString() })
      .eq("mp_subscription_id", payload.subscriptionId)
      .eq("status", "active");
  }
}

// ─── Prescription Fee Splitting ──────────────────────────────

/** Calculate fee for a prescription medication with club discount */
export async function calculatePrescriptionFee(
  patientId: string,
  medicationName: string,
  originalPrice: number,
): Promise<PrescriptionFee> {
  const membership = await getActiveMembership(patientId);
  const discountPct = membership?.plan?.prescriptionDiscount ?? 0;
  const finalPrice = Math.round(originalPrice * (1 - discountPct) * 100) / 100;

  return {
    id: "",
    patientId,
    medicationName,
    originalPrice,
    discountPct,
    finalPrice,
    clubPlanSlug: membership?.plan?.slug,
    paymentStatus: "pending",
    createdAt: new Date().toISOString(),
  };
}

/** Record a prescription fee charge */
export async function recordPrescriptionFee(
  fee: Omit<PrescriptionFee, "id" | "createdAt">,
): Promise<PrescriptionFee> {
  const supabase = await getSupabase();
  const { data, error } = await supabase
    .from("prescription_fees")
    .insert({
      patient_id: fee.patientId,
      prescription_id: fee.prescriptionId || null,
      medication_name: fee.medicationName,
      original_price: fee.originalPrice,
      discount_pct: fee.discountPct,
      final_price: fee.finalPrice,
      club_plan_slug: fee.clubPlanSlug || null,
      payment_status: fee.paymentStatus,
    })
    .select("*")
    .single();

  if (error || !data) {
    logger.error({ error }, "Failed to record prescription fee");
    throw new Error("Failed to record fee");
  }

  return {
    id: data.id,
    patientId: data.patient_id,
    prescriptionId: data.prescription_id,
    medicationName: data.medication_name,
    originalPrice: Number(data.original_price),
    discountPct: Number(data.discount_pct),
    finalPrice: Number(data.final_price),
    clubPlanSlug: data.club_plan_slug,
    paymentStatus: data.payment_status,
    createdAt: data.created_at,
  };
}

// ─── Welcome Plan (Plan de Bienvenida) ───────────────────────
// Included in ALL tiers. Gender-and-age-specific screening studies.

import type { WelcomeStudy, WelcomePlanResult, WelcomeStudyGender } from "@/lib/types";

const WELCOME_PLAN_STUDIES: WelcomeStudy[] = [
  // ── Shared (all genders) ──────────────────────────────────
  {
    id: "wp-ecg",
    name: "Electrocardiograma (ECG)",
    nameEn: "Electrocardiogram (ECG)",
    category: "cardio",
    gender: "all",
    description: "Registro de la actividad eléctrica del corazón en reposo.",
    descriptionEn: "Recording of the heart's electrical activity at rest.",
  },
  {
    id: "wp-eco",
    name: "Ecocardiograma",
    nameEn: "Echocardiogram",
    category: "cardio",
    gender: "all",
    description: "Ecografía cardíaca para evaluar estructura y función del corazón.",
    descriptionEn: "Cardiac ultrasound to assess heart structure and function.",
  },
  {
    id: "wp-ergo",
    name: "Ergometría",
    nameEn: "Stress Test (Ergometry)",
    category: "cardio",
    gender: "all",
    description: "Prueba de esfuerzo en cinta para evaluar respuesta cardiovascular.",
    descriptionEn: "Treadmill stress test to evaluate cardiovascular response.",
  },

  // ── Male-specific ─────────────────────────────────────────
  {
    id: "wp-rx-torax",
    name: "Radiografía de Tórax",
    nameEn: "Chest X-Ray",
    category: "imaging",
    gender: "male",
    description: "Imagen del tórax para evaluar pulmones, corazón y estructuras óseas.",
    descriptionEn: "Chest image to evaluate lungs, heart, and bone structures.",
  },
  {
    id: "wp-eco-prostatica",
    name: "Ecografía Prostática",
    nameEn: "Prostate Ultrasound",
    category: "screening",
    gender: "male",
    minAge: 45,
    description: "Ecografía transabdominal de próstata. Recomendada a partir de los 45 años.",
    descriptionEn: "Transabdominal prostate ultrasound. Recommended from age 45.",
  },
  {
    id: "wp-doppler-cuello",
    name: "Doppler de Vasos de Cuello",
    nameEn: "Neck Vessels Doppler",
    category: "cardio",
    gender: "male",
    minAge: 45,
    description:
      "Ecografía Doppler de arterias carótidas y vertebrales para evaluar flujo sanguíneo.",
    descriptionEn: "Doppler ultrasound of carotid and vertebral arteries to assess blood flow.",
  },

  // ── Female-specific ───────────────────────────────────────
  {
    id: "wp-eco-mamaria",
    name: "Ecografía Mamaria",
    nameEn: "Breast Ultrasound",
    category: "screening",
    gender: "female",
    description: "Ecografía bilateral de mamas para detección temprana.",
    descriptionEn: "Bilateral breast ultrasound for early detection.",
  },
  {
    id: "wp-eco-gineco",
    name: "Ecografía Ginecológica",
    nameEn: "Gynecological Ultrasound",
    category: "screening",
    gender: "female",
    description: "Ecografía pélvica transabdominal para evaluación ginecológica.",
    descriptionEn: "Transabdominal pelvic ultrasound for gynecological evaluation.",
  },
  {
    id: "wp-lab-fem",
    name: "Laboratorio Completo",
    nameEn: "Complete Bloodwork",
    category: "lab",
    gender: "female",
    description: "Hemograma, glucemia, perfil lipídico, función renal, hepática y tiroidea.",
    descriptionEn: "CBC, glucose, lipid panel, renal, hepatic and thyroid function.",
  },
];

/** Get welcome plan studies for a specific patient profile */
export function getWelcomePlanStudies(gender: WelcomeStudyGender, age?: number): WelcomePlanResult {
  const genderStudies = WELCOME_PLAN_STUDIES.filter(
    (s) => s.gender === "all" || s.gender === gender,
  );

  const baseStudies = genderStudies.filter((s) => !s.minAge);
  const ageSpecificStudies = genderStudies.filter(
    (s) => s.minAge !== undefined && age !== undefined && age >= s.minAge,
  );

  return {
    baseStudies,
    ageSpecificStudies,
    allStudies: [...baseStudies, ...ageSpecificStudies],
  };
}

/** Get all welcome plan studies (for display when gender/age unknown) */
export function getAllWelcomePlanStudies(): WelcomeStudy[] {
  return WELCOME_PLAN_STUDIES;
}

// ─── Mappers ─────────────────────────────────────────────────

function mapPlan(row: Record<string, unknown>): ClubPlan {
  const r = row as Record<string, string | number | boolean | null>;
  return {
    id: r.id as string,
    slug: r.slug as ClubPlan["slug"],
    nameEs: r.name_es as string,
    nameEn: r.name_en as string,
    priceArs: Number(r.price_ars),
    priceUsd: Number(r.price_usd),
    prescriptionDiscount: 0, // legacy — removed
    maxTeleconsultas: r.max_teleconsultas as number,
    includesDelivery: r.includes_delivery as boolean,
    includesCoraPriority: r.includes_cora_priority as boolean,
    includesRecordsRequest: true, // all plans include records request
    active: r.active as boolean,
    sortOrder: r.sort_order as number,
  };
}

function mapMembership(row: Record<string, unknown>): ClubMembership {
  const r = row as Record<string, string | number | boolean | null | Record<string, unknown>>;
  return {
    id: r.id as string,
    memberId: (r.member_id as string) || "",
    patientId: r.patient_id as string,
    planId: r.plan_id as string,
    plan: r.club_plans ? mapPlan(r.club_plans as Record<string, unknown>) : undefined,
    status: r.status as ClubMembership["status"],
    mpSubscriptionId: (r.mp_subscription_id as string) || undefined,
    startedAt: r.started_at as string,
    expiresAt: (r.expires_at as string) || undefined,
    cancelledAt: (r.cancelled_at as string) || undefined,
  };
}
